### ISSUE TITLE
new collaborations?

### ISSUE THREAD

**Issue by ghost** [isaacarnault/installations#1]

**Comment by isaacarnault** [comment]
Hi @lucasnuic, eventually.
 Which tool(s) would you like to reference? Or would you like to improve the current ones?

**Comment by isaacarnault** [comment]
> > Which tool(s) would you like to reference? Or would you like to improve the current ones?
> 
> can I add r language here?

Yes if you want. Thanks.

**Comment by isaacarnault** [comment]
> > Yes if you want. Thanks.
> 
> If I submit a pull request, will you accept it?

I've invited you to this repository. Can you please check your mail and confirm?

**Comment by isaacarnault** [comment]
> > Yes if you want. Thanks.
> 
> If I submit a pull request, will you accept it?

yes, I should be able to do it from here
